# Generated by Django 3.2 on 2021-04-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_appid'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoddean',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
