# Generated by Django 3.2 on 2021-04-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_hoddean_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='deanapp',
            fields=[
                ('app_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pro_id', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='dirapp',
            fields=[
                ('app_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pro_id', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='hodapp',
            fields=[
                ('app_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pro_id', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
